CREATE PROCEDURE Food_Select_Details_Exp ()
--
MODIFIES SQL DATA
DYNAMIC RESULT SETS 1
BEGIN ATOMIC
--
DECLARE result CURSOR
FOR
--
SELECT food_id,
       food_name,
       carbohydrates_carbs_by_diff,
       carbohydrates_digestible,
       carbohydrates_fiber,
       carbohydrates_fiber_insoluble,
       carbohydrates_fiber_soluble,
       carbohydrates_fructose,
       carbohydrates_glucose,
       carbohydrates_glycemic_load,
       carbohydrates_lactose,
       carbohydrates_starch,
       carbohydrates_sucrose,
       carbohydrates_sugars,
       energy_alcohol,
       energy_carbohydrate,
       energy_dha,--
       energy_digestible,
       energy_epa,--
       energy_fat,
       energy_fat_and_carbohydrate,
       energy_gross,
       energy_hcsfa,--
       energy_lcn3pufa,--
       energy_linoleic,--
       energy_linolenic,--
       energy_monounsaturated,--
       energy_polyunsaturated,--
       energy_protein,
       energy_protein_and_carbohydrate,--
       energy_saturated,--
       fats_cholesterol,
       fats_dha,
       fats_epa,
       fats_hcsfa,
       fats_lauric,
       fats_lcn3pufa,
       fats_linoleic,
       fats_linolenic,
       fats_monounsaturated,
       fats_myristic,
       fats_palmitic,
       fats_polyunsaturated,
       fats_saturated,
       fats_stearic,
       fats_total,
       minerals_calcium,
       minerals_copper,
       minerals_iron,
       minerals_magnesium,
       minerals_manganese,
       minerals_phosphorus,
       minerals_potassium,
       minerals_selenium,
       minerals_sodium,
       minerals_zinc,
       other_alcohol,
       other_cost,
       other_water,
       other_weight,
       phytonutrients_anthocyanins,
       phytonutrients_beta_carotene,
       phytonutrients_caffeine,
       phytonutrients_carotenoids,
       phytonutrients_flavanols,
       phytonutrients_flavanones,
       phytonutrients_flavones,
       phytonutrients_flavonoids,
       phytonutrients_flavonols,
       phytonutrients_gamma_tocopherol,
       phytonutrients_isoflavones,
       phytonutrients_lutein_zeaxanthin,
       phytonutrients_lycopene,
       phytonutrients_phytosterols,
       phytonutrients_theobromine,
       protein_complete,
       protein_total,
       vitamins_choline,
       vitamins_folate,
       vitamins_niacin,
       vitamins_pantothenic_acid,
       vitamins_riboflavin,
       vitamins_thiamin,
       vitamins_vitamin_a,
       vitamins_vitamin_b6,
       vitamins_vitamin_b12,
       vitamins_vitamin_c,
       vitamins_vitamin_d,
       vitamins_vitamin_e,
       vitamins_vitamin_k
FROM DnFoodFact
ORDER BY food_name;
--
OPEN RESULT;
--
END;
/
