SELECT ROUTINE_NAME
FROM   INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA = 'PUBLIC'
ORDER BY ROUTINE_NAME;
/
SELECT ROUTINE_SCHEMA,ROUTINE_NAME,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME
FROM   INFORMATION_SCHEMA.ROUTINE_COLUMN_USAGE;
/
SELECT  ROUTINE_NAME,ROUTINE_TYPE,ROUTINE_DEFINITION
FROM   INFORMATION_SCHEMA.ROUTINES a
WHERE SPECIFIC_SCHEMA = 'PUBLIC'
ORDER BY ROUTINE_NAME;
/
SELECT * 
FROM
INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE;
/
SELECT * 
FROM
INFORMATION_SCHEMA.ROUTINE_SEQUENCE_USAGE;
/
SELECT CONCAT('"',ROUTINE_NAME,'"'),'->',CONCAT('"',TABLE_NAME,'";')
FROM
INFORMATION_SCHEMA.ROUTINE_TABLE_USAGE;
/
SELECT * 
FROM
INFORMATION_SCHEMA.TABLES;
/
SELECT * 
FROM
INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS;
/
SELECT * 
FROM
INFORMATION_SCHEMA.TRIGGER_ROUTINE_USAGE;
/
SELECT * 
FROM
INFORMATION_SCHEMA.TRIGGER_TABLE_USAGE;
/
SELECT * 
FROM
INFORMATION_SCHEMA.TRIGGERS;
/
SELECT CONCAT('"',a.ROUTINE_NAME,'"'),'->',CONCAT('"',b.ROUTINE_NAME,'";')
FROM   INFORMATION_SCHEMA.ROUTINES a,INFORMATION_SCHEMA.ROUTINES b, INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE c
WHERE a.SPECIFIC_NAME = c.SPECIFIC_NAME
AND b.SPECIFIC_NAME = c.ROUTINE_NAME
/
SELECT a.ROUTINE_NAME,b.ROUTINE_NAME as DEPENDENT
FROM   INFORMATION_SCHEMA.ROUTINES a,INFORMATION_SCHEMA.ROUTINES b, INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE c
WHERE a.SPECIFIC_NAME = c.SPECIFIC_NAME
AND b.SPECIFIC_NAME = c.ROUTINE_NAME
AND ROUTINE_SCHEMA = 'PUBLIC'
ORDER BY a.ROUTINE_NAME,b.ROUTINE_NAME
/
SELECT b.ROUTINE_NAME as dependent,a.ROUTINE_NAME as routine
FROM   INFORMATION_SCHEMA.ROUTINES a,INFORMATION_SCHEMA.ROUTINES b, INFORMATION_SCHEMA.ROUTINE_ROUTINE_USAGE c
WHERE a.SPECIFIC_NAME = c.SPECIFIC_NAME
AND b.SPECIFIC_NAME = c.ROUTINE_NAME
AND ROUTINE_SCHEMA = 'PUBLIC'
ORDER BY b.ROUTINE_NAME,a.ROUTINE_NAME
/
EXPLAIN REFERENCES TO TABLE FOOD;
/
EXPLAIN REFERENCES TO SPECIFIC ROUTINE FOOD_DELETE_11265;
/
SELECT TABLE_NAME,ROUTINE_NAME
FROM
INFORMATION_SCHEMA.ROUTINE_TABLE_USAGE
WHERE ROUTINE_SCHEMA = 'PUBLIC'
ORDER BY TABLE_NAME;
/
